version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@db
      MYSQL_DATABASE: navjivan-db
      MYSQL_USER: akshat
      MYSQL_PASSWORD: akshat@db
    ports:
      - "3307:3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  project:
    build: .
    image: mycode
    container_name: my-django-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql