"""navjivan URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
    SpectacularRedocView,
)

# RapiDoc is not in drf_spectacular.views by default in older versions, 
# but we can try to import it or use a custom view if needed.
# Actually, drf-spectacular supports it.
try:
    from drf_spectacular.views import SpectacularRapiDocView
except ImportError:
    SpectacularRapiDocView = None

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    # API v1
    path('api/v1/', include(([
        path('', include('accounts.urls')),
        path('', include('profiles.urls')),
        path('', include('education.urls')),
        path('', include('government_ids.urls')),
        path('', include('documents.urls')),
        path('', include('audit_logs.urls')),
        path('auth/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
        path('auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    ], 'api'), namespace='v1')),

    # OpenAPI schema
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

if SpectacularRapiDocView:
    urlpatterns += [
        path('api/rapidoc/', SpectacularRapiDocView.as_view(url_name='schema'), name='rapidoc'),
    ]

urlpatterns += [
    # Keep existing client pages if needed; no frontend is generated by this project
    path('', include('clients.urls')),
]
