# Generated by Django 5.0.4 on 2024-04-06 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=20, unique=True)),
                ('surname', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=10)),
                ('cast', models.CharField(choices=[('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC'), ('ews', 'EWS'), ('general', 'GENERAL')], max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('taluka', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('height', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('chest', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('edu_qualification', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='Photos-Signature/')),
                ('signature', models.ImageField(upload_to='Photos-Signature/')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_certificate_number', models.CharField(max_length=20)),
                ('cast_certificate_date', models.DateField()),
                ('cast_certificate_img', models.FileField(upload_to='Documents/')),
                ('obc_certificate_number', models.CharField(max_length=20)),
                ('obc_certificate_date', models.DateField()),
                ('obc_certificate_provider', models.CharField(max_length=20)),
                ('obc_certificate_img', models.FileField(upload_to='Documents/')),
                ('aadhar_card_number', models.CharField(max_length=20)),
                ('aadhar_card_img', models.FileField(upload_to='Documents/')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClientQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('board', models.CharField(max_length=50)),
                ('passing_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('attempt', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('marksheet', models.FileField(upload_to='Marksheets/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='clients.clientprofile')),
            ],
        ),
    ]
