# Generated by Django 5.0.4 on 2024-04-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='unique_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
