# Generated by Django 4.2.28 on 2026-02-20 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import education.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ssc', 'SSC'), ('hsc', 'HSC'), ('graduation', 'Graduation'), ('post_graduation', 'Post Graduation')], max_length=32)),
                ('board', models.CharField(max_length=255)),
                ('passing_year', models.PositiveSmallIntegerField(db_index=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marksheet', models.FileField(blank=True, null=True, upload_to=education.models.marksheet_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'level'], name='education_e_user_id_c736ec_idx'), models.Index(fields=['passing_year'], name='education_e_passing_76d9af_idx')],
            },
        ),
    ]
